     title: Philipps Blog
     description: Gedanken, Projekte und alles dazwischen · [@TechnikWeber](https://github.com/TechnikWeber)
     author: Philipp Weber
     url: https://TechnikWeber.github.io    # kanonische Adresse der Seite
     theme: minima
     plugins:
       - jekyll-feed      # erzeugt automatisch einen RSS-Feed
       - jekyll-seo-tag   # SEO-Metadaten
       
     # Minima zeigt Seiten mit diesem Eintrag in der Navigation
     header_pages:
     - impressum.md
     - datenschutz.md
